[package]
name = "falconos"
version = "0.1.0"
authors = ["Erik Davidson <erik@erikd.org>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1"
spin = "0.3.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"